spring.application.name=mednetExternalPACS
spring.main.web-application-type=servlet

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.port=8091

spring.config.import=optional:file:/usr/local/mednet/mednetFiles/config/propertiesFile/MednetExternalPACS.properties

logging.level.root=INFO

externalpacs.cors.allowed-origins=*

mednet.lab.internal.url=http://localhost:9999/mednetLab
