package com.mednet.externalpacs.common.util;

public interface APIErrorCodes {

    int ERR_CODE_BAD_REQUEST = 400;
    int ERR_CODE_SOMETHING_WENT_WRONG = 500;
    int ERR_CODE_FORBIDDEN = 403;
    int ERR_CODE_NOT_FOUND = 404;

    String ERR_MSG_SOMETHING_WENT_WRONG = "SOMETHING WENT WRONG. PLEASE TRY AGAIN LATER.";
    String ERR_MSG_INVALID_INPUT_DATA = "INVALID INPUT DATA.";
    String ERR_MSG_RECORD_NOT_FOUND = "RECORD NOT FOUND.";
    String ERR_MSG_INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR.";
}
